# Generated by Django 3.2 on 2023-04-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('observation', models.CharField(blank=True, max_length=150)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('last_replacement', models.DateField(null=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
