# Generated by Django 3.2 on 2023-04-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_material_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='id',
            field=models.BigIntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False),
        ),
    ]
