# Generated by Django 3.2 on 2023-04-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('done', models.BooleanField(default=False)),
                ('max_date', models.DateField(null=True)),
            ],
        ),
    ]
